language: csharp
mono: none
dotnet: 2.2
sudo: false
env:
    global:
        - DOTNET_CLI_TELEMETRY_OPTOUT: 1
script:
    - echo "Building package 1.0.$TRAVIS_BUILD_NUMBER"
    - dotnet restore src/
    - dotnet pack src -c Release -o dist /p:Version=1.0.$TRAVIS_BUILD_NUMBER
