language: csharp
mono: none
dotnet: 3.0
sudo: false
env:
    global:
        - DOTNET_CLI_TELEMETRY_OPTOUT: 1

script: dotnet restore src/
script: dotnet test src/
script: dotnet pack src -c Release -o dist /p:Version=1.0.$TRAVIS_BUILD_NUMBER
