language: csharp
mono: none
dotnet: 3.0
sudo: false
env:
    global:
        - DOTNET_CLI_TELEMETRY_OPTOUT: 1

stages:
  - test
  - name: deploy
    if: branch = master
jobs:
  include:
    - stage: test
      script: dotnet test src/
    - state: deploy
      script: dotnet pack src -c Release -o dist /p:Version=1.0.$TRAVIS_BUILD_NUMBER
