name: Build and Test

on: [push]

jobs: 
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      
      - name: build and test
        run: |
          cd src
          dotnet test DeepWinter.RRuleParserNet.sln